  ---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При регистрации аккаунта пользователь обязан указывать номер телефона
  - Переход в другие разделы магазина должен происходить без перезагрузки сайта
  - Нельзя зарегистрировать больше одного аккаунта с одинаковыми никнеймом, номером телефона и почты (опционально)
  - При указании цены продукта в корзине помимо обычной цены должна показываться цена с учетом скидки, если таковая есть
  - При переключении языка ВЕСЬ текст должен переводиться на выбранный язык