  ---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Помимо функциональности, сайт должен иметь привлекательный и современный дизайн, который будет привлекать пользователей и создавать благоприятное впечатление о бренде.
  - Несмотря на то, что функциональность фильтрации и поиска присутствует, сайт должен предложить пользователю простую и понятную навигацию, чтобы пользователи могли легко находить нужные товары.
  - Необходимо обеспечить высокий уровень безопасности для защиты личной информации пользователей, включая данные о платежах и личные данные.
  - Сайт должен иметь оптимизированный код и ресурсы для обеспечения быстрой загрузки страниц, что важно для удобства пользователей и для улучшения позиций сайта в поисковых системах.
  - Для обеспечения возможности масштабирования и поддержания высокой производительности при росте трафика, архитектура сайта должна быть гибкой и масштабируемой.
  - Для привлечения внимания пользователей и увеличения конверсии, изображения товаров должны быть высокого качества и позволять пользователю рассмотреть товар подробно.
  - В случае, если пользователь решит оформить заказ, сайт должен поддерживать различные методы оплаты, чтобы обеспечить удобство и безопасность процесса оплаты.
  - Интерфейс интернет-магазина должен быть центрирован на странице
  - При нажатии в любое место на экране после нажатия кнопки "Language/Язык" всплывающее окно со сменой языка должно закрываться
  - При указании цены продукта в корзине помимо обычной цены должна показываться цена с учетом скидки, если таковая есть
  - При регистрации аккаунта пользователь обязан указывать номер телефона
  - Переход в другие разделы магазина должен происходить без перезагрузки сайта
  - При переключении языка весь текст должен переводиться на выбранный язык
  - Нельзя зарегистрировать больше одного аккаунта с одинаковыми никнеймом, номером телефона и почтой (опционально)
  - При сортировке по цене должна учитываться цена со скидкой